package com.wonders.webservice.datacenter;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DataImportAPIService service = new DataImportAPIService();
 * DataImportAPIDelegate portType = service.getDataImportAPIHandler();
 * portType.setDataInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DataImportAPIService", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", wsdlLocation = "http://10.1.48.40/service/DataImport_API_Handler?wsdl")
public class DataImportAPIService extends Service {

	private final static URL DATAIMPORTAPISERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(DataImportAPIService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = DataImportAPIService.class.getResource(".");
			url = new URL(baseUrl,
					"http://10.1.48.40/service/DataImport_API_Handler?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.1.48.40/service/DataImport_API_Handler?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DATAIMPORTAPISERVICE_WSDL_LOCATION = url;
	}

	public DataImportAPIService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DataImportAPIService() {
		super(DATAIMPORTAPISERVICE_WSDL_LOCATION, new QName(
				"http://dataExchange.webservice.stpt.wondersgroup.com/",
				"DataImportAPIService"));
	}

	/**
	 * 
	 * @return returns DataImportAPIDelegate
	 */
	@WebEndpoint(name = "DataImport_API_Handler")
	public DataImportAPIDelegate getDataImportAPIHandler() {
		return super.getPort(new QName(
				"http://dataExchange.webservice.stpt.wondersgroup.com/",
				"DataImport_API_Handler"), DataImportAPIDelegate.class);
	}

}
