package com.wonders.webservice.datacenter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DataImportAPIDelegate", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/")
public interface DataImportAPIDelegate {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setDataInfo", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", className = "com.wonders.webservice.datacenter.SetDataInfo")
	@ResponseWrapper(localName = "setDataInfoResponse", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", className = "com.wonders.webservice.datacenter.SetDataInfoResponse")
	public String setDataInfo(
            @WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2,
            @WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDataInfo", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", className = "com.wonders.webservice.datacenter.GetDataInfo")
	@ResponseWrapper(localName = "getDataInfoResponse", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", className = "com.wonders.webservice.datacenter.GetDataInfoResponse")
	public String getDataInfo(
            @WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "confirmGetDataInfo", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", className = "com.wonders.webservice.datacenter.ConfirmGetDataInfo")
	@ResponseWrapper(localName = "confirmGetDataInfoResponse", targetNamespace = "http://dataExchange.webservice.stpt.wondersgroup.com/", className = "com.wonders.webservice.datacenter.ConfirmgetDataInfoResponse")
	public String confirmGetDataInfo(
            @WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2,
            @WebParam(name = "arg3", targetNamespace = "") String arg3);

}
